-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 17:35:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema selecDes_BL_colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema selecDes_BL_colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `selecDes_BL_colegio` DEFAULT CHARACTER SET utf8 ;
USE `selecDes_BL_colegio` ;

-- -----------------------------------------------------
-- Table `selecDes_BL_colegio`.`colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selecDes_BL_colegio`.`colegio` (
  `idcolegio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcolegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selecDes_BL_colegio`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selecDes_BL_colegio`.`asignatura` (
  `idasignatura` INT NOT NULL AUTO_INCREMENT,
  `idColegio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idasignatura`),
  INDEX `fk_asignatura_colegio_idx` (`idColegio` ASC),
  CONSTRAINT `fk_asignatura_colegio`
    FOREIGN KEY (`idColegio`)
    REFERENCES `selecDes_BL_colegio`.`colegio` (`idcolegio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selecDes_BL_colegio`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selecDes_BL_colegio`.`profesor` (
  `idprofesor` INT NOT NULL AUTO_INCREMENT,
  `idAsignatura` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `asignatura` VARCHAR(20) NOT NULL,
  `activo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idprofesor`),
  INDEX `fk_profesor_asignatura_idx` (`idAsignatura` ASC),
  CONSTRAINT `fk_profesor_asignatura`
    FOREIGN KEY (`idAsignatura`)
    REFERENCES `selecDes_BL_colegio`.`asignatura` (`idasignatura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selecDes_BL_colegio`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selecDes_BL_colegio`.`alumno` (
  `idalumno` INT NOT NULL AUTO_INCREMENT,
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`idalumno`),
  INDEX `fk_alumno_profesor_idx` (`idProfesor` ASC),
  CONSTRAINT `fk_alumno_profesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `selecDes_BL_colegio`.`profesor` (`idprofesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selecDes_BL_colegio`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selecDes_BL_colegio`.`nota` (
  `idnota` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `nota` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idnota`),
  INDEX `fk_nota_Alumno_idx` (`idAlumno` ASC),
  CONSTRAINT `fk_nota_Alumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `selecDes_BL_colegio`.`alumno` (`idalumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
